#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x92EDB04BFF325CF3 (brobecker@adacore.com)
#
%define keepstatic 1
Name     : gdb
Version  : 8.1
Release  : 68
URL      : https://mirrors.kernel.org/gnu/gdb/gdb-8.1.tar.xz
Source0  : https://mirrors.kernel.org/gnu/gdb/gdb-8.1.tar.xz
Source99 : https://mirrors.kernel.org/gnu/gdb/gdb-8.1.tar.xz.sig
Summary  : zlib compression library
Group    : Development/Tools
License  : BSL-1.0 GFDL-1.1 GPL-1.0+ GPL-2.0 GPL-2.0+ GPL-3.0 GPL-3.0+ LGPL-2.0 LGPL-2.0+ LGPL-2.1 LGPL-3.0 Public-Domain
Requires: gdb-bin
Requires: gdb-data
Requires: gdb-doc
BuildRequires : binutils-dev
BuildRequires : bison
BuildRequires : dejagnu
BuildRequires : expat-dev
BuildRequires : expect
BuildRequires : flex
BuildRequires : gcc-libgcc32
BuildRequires : glibc-dev32
BuildRequires : glibc-staticdev
BuildRequires : go
BuildRequires : libxslt-bin
BuildRequires : mpfr-dev
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(zlib)
BuildRequires : processor-trace-dev
BuildRequires : procps-ng
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : sed
BuildRequires : tcl
BuildRequires : texinfo
BuildRequires : xz-dev
Patch1: cve-2017-9778.patch

%description
This directory contains various GNU compilers, assemblers, linkers,
debuggers, etc., plus their support routines, definitions, and documentation.

%package bin
Summary: bin components for the gdb package.
Group: Binaries
Requires: gdb-data

%description bin
bin components for the gdb package.


%package data
Summary: data components for the gdb package.
Group: Data

%description data
data components for the gdb package.


%package dev
Summary: dev components for the gdb package.
Group: Development
Requires: gdb-bin
Requires: gdb-data
Provides: gdb-devel

%description dev
dev components for the gdb package.


%package doc
Summary: doc components for the gdb package.
Group: Documentation

%description doc
doc components for the gdb package.


%prep
%setup -q -n gdb-8.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1520914172
export CFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs "
export FCFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs "
export FFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong -mzero-caller-saved-regs "
%configure  --enable-static  --with-separate-debug-dir=/usr/lib/debug --enable-tui --enable-targets=%{_arch}-unknown-linux-gnu,%{_arch}-generic-linux-gnu  --target=%{_arch}-generic-linux-gnu %{_arch}-generic-linux-gnu --with-python=yes --enable-plugins --disable-rpath --with-system-zlib --with-intel-pt PYTHON=/usr/bin/python3 --with-python=/usr/bin/python3
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1520914172
rm -rf %{buildroot}
%make_install
## make_install_append content
rm -f %{buildroot}/usr/share/locale/*/LC_MESSAGES/bfd.mo
rm -f %{buildroot}/usr/share/locale/*/LC_MESSAGES/opcodes.mo
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gcore
/usr/bin/gdb
/usr/bin/gdbserver

%files data
%defattr(-,root,root,-)
/usr/share/gdb/python/gdb/FrameDecorator.py
/usr/share/gdb/python/gdb/FrameIterator.py
/usr/share/gdb/python/gdb/__init__.py
/usr/share/gdb/python/gdb/__pycache__/FrameDecorator.cpython-36.pyc
/usr/share/gdb/python/gdb/__pycache__/FrameIterator.cpython-36.pyc
/usr/share/gdb/python/gdb/__pycache__/__init__.cpython-36.pyc
/usr/share/gdb/python/gdb/__pycache__/frames.cpython-36.pyc
/usr/share/gdb/python/gdb/__pycache__/printing.cpython-36.pyc
/usr/share/gdb/python/gdb/__pycache__/prompt.cpython-36.pyc
/usr/share/gdb/python/gdb/__pycache__/types.cpython-36.pyc
/usr/share/gdb/python/gdb/__pycache__/unwinder.cpython-36.pyc
/usr/share/gdb/python/gdb/__pycache__/xmethod.cpython-36.pyc
/usr/share/gdb/python/gdb/command/__init__.py
/usr/share/gdb/python/gdb/command/__pycache__/__init__.cpython-36.pyc
/usr/share/gdb/python/gdb/command/__pycache__/explore.cpython-36.pyc
/usr/share/gdb/python/gdb/command/__pycache__/frame_filters.cpython-36.pyc
/usr/share/gdb/python/gdb/command/__pycache__/pretty_printers.cpython-36.pyc
/usr/share/gdb/python/gdb/command/__pycache__/prompt.cpython-36.pyc
/usr/share/gdb/python/gdb/command/__pycache__/type_printers.cpython-36.pyc
/usr/share/gdb/python/gdb/command/__pycache__/unwinders.cpython-36.pyc
/usr/share/gdb/python/gdb/command/__pycache__/xmethods.cpython-36.pyc
/usr/share/gdb/python/gdb/command/explore.py
/usr/share/gdb/python/gdb/command/frame_filters.py
/usr/share/gdb/python/gdb/command/pretty_printers.py
/usr/share/gdb/python/gdb/command/prompt.py
/usr/share/gdb/python/gdb/command/type_printers.py
/usr/share/gdb/python/gdb/command/unwinders.py
/usr/share/gdb/python/gdb/command/xmethods.py
/usr/share/gdb/python/gdb/frames.py
/usr/share/gdb/python/gdb/function/__init__.py
/usr/share/gdb/python/gdb/function/__pycache__/__init__.cpython-36.pyc
/usr/share/gdb/python/gdb/function/__pycache__/as_string.cpython-36.pyc
/usr/share/gdb/python/gdb/function/__pycache__/caller_is.cpython-36.pyc
/usr/share/gdb/python/gdb/function/__pycache__/strfns.cpython-36.pyc
/usr/share/gdb/python/gdb/function/as_string.py
/usr/share/gdb/python/gdb/function/caller_is.py
/usr/share/gdb/python/gdb/function/strfns.py
/usr/share/gdb/python/gdb/printer/__init__.py
/usr/share/gdb/python/gdb/printer/__pycache__/__init__.cpython-36.pyc
/usr/share/gdb/python/gdb/printer/__pycache__/bound_registers.cpython-36.pyc
/usr/share/gdb/python/gdb/printer/bound_registers.py
/usr/share/gdb/python/gdb/printing.py
/usr/share/gdb/python/gdb/prompt.py
/usr/share/gdb/python/gdb/types.py
/usr/share/gdb/python/gdb/unwinder.py
/usr/share/gdb/python/gdb/xmethod.py
/usr/share/gdb/syscalls/aarch64-linux.xml
/usr/share/gdb/syscalls/amd64-linux.xml
/usr/share/gdb/syscalls/arm-linux.xml
/usr/share/gdb/syscalls/freebsd.xml
/usr/share/gdb/syscalls/gdb-syscalls.dtd
/usr/share/gdb/syscalls/i386-linux.xml
/usr/share/gdb/syscalls/mips-n32-linux.xml
/usr/share/gdb/syscalls/mips-n64-linux.xml
/usr/share/gdb/syscalls/mips-o32-linux.xml
/usr/share/gdb/syscalls/ppc-linux.xml
/usr/share/gdb/syscalls/ppc64-linux.xml
/usr/share/gdb/syscalls/s390-linux.xml
/usr/share/gdb/syscalls/s390x-linux.xml
/usr/share/gdb/syscalls/sparc-linux.xml
/usr/share/gdb/syscalls/sparc64-linux.xml
/usr/share/gdb/system-gdbinit/elinos.py
/usr/share/gdb/system-gdbinit/wrs-linux.py

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/ansidecl.h
%exclude /usr/include/bfd.h
%exclude /usr/include/bfdlink.h
%exclude /usr/include/dis-asm.h
%exclude /usr/include/plugin-api.h
%exclude /usr/include/symcat.h
/usr/include/gdb/jit-reader.h
/usr/lib64/*.a
/usr/lib64/libinproctrace.so

%files doc
%defattr(-,root,root,-)
%doc /usr/share/info/*
%doc /usr/share/man/man1/*
%doc /usr/share/man/man5/*
%exclude /usr/share/info/bfd.info
